# Generated by Django 5.1.1 on 2025-12-16 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_achievement_alter_cat_options_alter_cat_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='achivement',
            new_name='achievements',
        ),
    ]
